apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-tester-2121-files
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2121-files
    version: 1.0.0
    managed-by: kubectl
spec:
  capacity:
    storage: 2Gi  # 표준화된 단위 사용
  volumeMode: Filesystem
  storageClassName: local-storage 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # PVC 삭제 후에도 PV 유지
  local:
    path: "/mnt/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - uc-master
                - uc-node1
                - uc-node2  # 모든 노드에서 사용할 수 있도록 추가
