apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: anotherclass-212
  name: api-tester-2121-files
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2121
    version: 1.0.0
    managed-by: kubectl
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
